apiVersion: v1
kind: ConfigMap
metadata:
  name: hivegate-config
data:
  db-host: "postgres-service"
  db-port: "5432"
  db-database: "hivegate"
---
apiVersion: v1
kind: Secret
metadata:
  name: hivegate-db
type: Opaque
stringData:
  username: "agadmin"
  password: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: hivegate-secrets
type: Opaque
stringData:
  token-encryption-key: "CHANGE_ME_BASE64_FERNET_KEY"
